name: ChangHyeon Nam's Blog
url: https://changhyeonnam.github.io
description: 'tech blog'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'ChangHyeon Nam'
disqus_shortname: Nam
# google_analytics: G-NN7JP65RMS

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
